config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # read
  # Get all taks
  get 'tasks', to: 'tasks#index', as: :tasks

  # create
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'

  # edit
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit

  # read
  # Get one taks
  get 'tasks/:id', to: 'tasks#show', as: :task

  # update
  patch 'tasks/:id', to: 'tasks#update'

  # delete
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params).save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="m-3">
    <%= yield %>
  </body>
</html>

app/views/tasks/_checkbox.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input_field :completed, as: :boolean %>
<% end %>

app/views/tasks/_form.html.erb
<div class="border-bottom pb-4">
  <%= simple_form_for task do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <% if @task.new_record? == false %>
      <%= f.input :completed, as: :boolean, inline_label: 'Completed' %>
    <% end -%>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form", task: @task %>

<div class="mt-4">
  <%= link_to tasks_path do %>
    <%= fa_icon "undo" %>
    <%= "Back to list" %>
  <% end -%>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<div class="d-flex flex-column border-bottom pb-4 mt-3">
  <% @tasks.each do |task| %>
    <div class="d-flex">
      <%= simple_form_for task do |f| %>
        <%= f.input_field :completed, as: :boolean %>
      <% end %>
      <%= link_to task.title, task_path(task), class: "mx-2" %>
      <%= link_to (fa_icon "trash"), task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

<div class="mt-4 mx-2">
  <%= link_to tasks_new_path do %>
    <%= fa_icon "plus" %>
    <%= "Add a new task" %>
  <% end -%>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

app/views/tasks/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1> <%= @task.title %> </h1>
  <%= link_to task_edit_path, class: "btn btn-outline-secondary" do %>
    <%= fa_icon "pen" %>
    <%= "Edit this task" %>
  <% end -%>
</div>


<div class="bg-light border d-flex align-items-center p-4 rounded-sm">
  <p class="m-0"> <%= @task.details %> </p>
</div>

<div class="d-flex border-bottom mt-4">
  <%= render "checkbox", task: @task %>
  <% if @task.completed == true %>
    <p class="ml-2"> This task is completed</p>
    <% else %>
    <p class="ml-2">This task is not completed yet</p>
  <% end -%>
</div>

<div class="mt-4">
  <%= link_to tasks_path do %>
    <%= fa_icon "undo" %>
    <%= "Back to list" %>
  <% end -%>
</div>